name: Test Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: user/amiibo-memory-game:latest
